/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as EcofarmingRouteImport } from './routes/ecofarming'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const EcofarmingRoute = EcofarmingRouteImport.update({
  id: '/ecofarming',
  path: '/ecofarming',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/ecofarming': typeof EcofarmingRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/ecofarming': typeof EcofarmingRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/ecofarming': typeof EcofarmingRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/courses'
    | '/ecofarming'
    | '/gifts'
    | '/login'
    | '/species'
    | '/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/courses'
    | '/ecofarming'
    | '/gifts'
    | '/login'
    | '/species'
    | '/story'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/courses'
    | '/ecofarming'
    | '/gifts'
    | '/login'
    | '/species'
    | '/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRoute
  EcofarmingRoute: typeof EcofarmingRoute
  GiftsRoute: typeof GiftsRoute
  LoginRoute: typeof LoginRoute
  SpeciesRoute: typeof SpeciesRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecofarming': {
      id: '/ecofarming'
      path: '/ecofarming'
      fullPath: '/ecofarming'
      preLoaderRoute: typeof EcofarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRoute,
  EcofarmingRoute: EcofarmingRoute,
  GiftsRoute: GiftsRoute,
  LoginRoute: LoginRoute,
  SpeciesRoute: SpeciesRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
